# Matomo release action for automated PREVIEW releases
#
# Required GitHub secrets:
#
# GPG_CERTIFICATE  |  ASCII armored or Base64 encoded GPG certificate that is used to create the signatures for the archives
# GPG_CERTIFICATE_PASS  |  Passphrase of the GPG key

name: Build preview release

permissions:
  actions: none
  checks: none
  contents: write  # required to create tag and release
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  workflow_dispatch:
    branches:
      - 5.x-dev

jobs:
  preview-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          fetch-tags: true
          fetch-depth: 0

      - name: Prepare git config
        run: |
          cat <<- EOF > $HOME/.netrc
            machine github.com
            login $GITHUB_ACTOR
            password $GITHUB_TOKEN
            machine api.github.com
            login $GITHUB_ACTOR
            password $GITHUB_TOKEN
          EOF
          chmod 600 $HOME/.netrc
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if there are any changes to create a preview release for
        id: changes
        run: |
          git fetch origin 5.x-preview 5.x-dev -q
          
          LAST_MSG=$(git log -1 5.x-preview --pretty=format:"%s")
          echo $LAST_MSG
          PATTERN="^Update version to"
          if [[ "$LAST_MSG" =~ $PATTERN ]]; then
            echo 'matching pattern'
            DIFF=$(git diff 5.x-dev..5.x-preview^1)
          else
            echo 'non-matching pattern'
            DIFF=$(git diff 5.x-dev..5.x-preview)
          fi
          echo $DIFF
          
          if [ -z "$DIFF" ]; then
            echo "No changes since last preview version was created"
            DO_RELEASE=0
          else
            DO_RELEASE=1
          fi
          
          echo "do_release=$DO_RELEASE" >> $GITHUB_OUTPUT

      - name: Determine new preview version number
        id: version
        run: |
          git checkout 5.x-dev
          
          OLD_VERSION=$(php -r "include_once 'core/Version.php'; echo \Piwik\Version::VERSION;")
          NEW_VERSION=$(php -r "include_once 'core/Version.php'; \$v = new \Piwik\Version(); echo \$v->nextPreviewVersion(\Piwik\Version::VERSION);")
          
          if [ "$NEW_VERSION" == "" ]; then
            HAS_NEW_VERSION=0
          else
            HAS_NEW_VERSION=1
          fi
          
          PREVIEW_BRANCH="preview-${NEW_VERSION}"
          
          echo "OLD_VERSION=$OLD_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "PREVIEW_BRANCH=$PREVIEW_BRANCH" >> $GITHUB_ENV
          
          echo "has_new_version=$HAS_NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create a new branch
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        run: |
          git checkout -b $PREVIEW_BRANCH

      - name: Update version
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        run: |
          sed -i "s/VERSION = '${OLD_VERSION}';/VERSION = '${NEW_VERSION}';/g" core/Version.php
          cat core/Version.php

      - name: Commit version file changes
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        run: |
          git add core/Version.php
          git commit -m "Update version to ${NEW_VERSION}"

      - name: Push changes
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        run: |
          git push --set-upstream origin $PREVIEW_BRANCH

#      - name: Run tests for preview version branch
#      if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'

      - name: Merge into 5.x-preview
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        run: |
          git checkout -B 5.x-preview
          git merge --squash $PREVIEW_BRANCH
          git commit -m "Update version to ${NEW_VERSION}"
          git push --set-upstream origin 5.x-preview

      - name: Delete temporary preview release branch
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        run: |
          git branch -d $PREVIEW_BRANCH
          git push origin --delete $PREVIEW_BRANCH

#      - name: Import GPG key
#        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
#        id: import_gpg
#        run: |
#          echo "${{ secrets.GPG_CERTIFICATE }}" > $HOME/private.asc
#          gpg --import --batch --yes $HOME/private.asc
#          echo "default-cache-ttl 7200
#          max-cache-ttl 31536000
#          allow-preset-passphrase" > $HOME/.gnupg/gpg-agent.conf
#          keygrip=$(gpg --import --import-options show-only --with-keygrip $HOME/private.asc | grep "Keygrip" | grep -oP "([A-F0-9]+)" | head -1)
#          hexPassphrase=$( echo -n '${{ secrets.GPG_CERTIFICATE_PASS }}' | od -A n -t x1 -w100 | sed 's/ *//g' )
#          gpg-connect-agent "RELOADAGENT" /bye
#          gpg-connect-agent "PRESET_PASSPHRASE ${keygrip} -1 ${hexPassphrase}" /bye
#          gpg-connect-agent "KEYINFO ${keygrip}" /bye
#
      - name: Create tag, build and publish release
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        id: tag
        run: |
          echo "Version to build: '${NEW_VERSION}'"

          TAG_EXISTS=$( git tag --list "$NEW_VERSION" )
          if [[ -n "$TAG_EXISTS" ]]
          then
            echo "A tag for $tag_exists already exists."
            exit 1
          fi

          echo "Creating a tag for $NEW_VERSION"

          git tag $NEW_VERSION
          git push origin tags/$NEW_VERSION

          body="## Matomo ${version} (Pre-release)

          We recommend to read [this FAQ](https://matomo.org/faq/how-to-update/faq_159/) before using a pre-release in a production environment.

          Please use the attached archives for installing or updating Matomo.
          The source code download is only meant for developers and will require extra work to install it.
           - Latest stable production release can be found at https://matomo.org/download/ ([learn more](https://matomo.org/docs/installation/)) (recommended)
           - Beta and Release Candidate releases can be found at https://builds.matomo.org/ ([learn more](https://matomo.org/faq/how-to-update/faq_159/))"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

          cd $GITHUB_WORKSPACE
          chmod 755 ./.github/scripts/*.sh
          ./.github/scripts/build-package.sh $NEW_VERSION
        shell: bash

      - uses: ncipollo/release-action@v1
        if: steps.changes.outputs.do_release == '1' && steps.version.outputs.has_new_version == '1'
        with:
          artifacts: "archives/matomo-${{ steps.tag.outputs.version }}.*,archives/piwik-${{ steps.tag.outputs.version }}.*"
          allowUpdates: false
          tag: ${{ steps.tag.outputs.version }}
          body: "${{ steps.tag.outputs.body }}"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
